name: Android CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    workflow_dispatch: #Allow triggering builds manually from Actions tab in GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: false

    # NDK installation https://github.com/actions/runner-images/issues/60
    - name: Setup Android NDKv2
      run: ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.0.7026061"
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # Manually download library uploaded in mock release:
    # https://github.com/pktiuk/rosettadrone/releases/tag/libffm
    - name: Download libffmpeg library (workaround for https://github.com/RosettaDrone/rosettadrone/issues/141 )
      run: |
        wget https://github.com/pktiuk/rosettadrone/releases/download/libffmpeg/libffmpeg.zip
        unzip ./libffmpeg.zip 
        mv ./arm64-v8a/libffmpeg.so ./app/src/main/cpp/lib/arm64-v8a/
        mv ./armeabi-v7a/libffmpeg.so ./app/src/main/cpp/lib/armeabi-v7a/

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Copy mock keys
      run: cp ./.github/workflows/mock_keys.xml ./app/src/main/res/values/keys.xml
    - name: Build with Gradle
      run: ./gradlew build
